/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d45f1298-338b-45a6-8d35-1ac182e61744",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "f8ebab91cac640a7be1b477498fa8d60",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
